name: Deploy to PRODUCTION EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Save EC2 SSH private key
        run: |
          echo "${{ secrets.EC2_PROD_SSH_KEY }}" > prod-key.pem
          chmod 600 prod-key.pem

      - name: Deploy to Production EC2
        run: |
          echo "Cleaning old app..."
          ssh -o StrictHostKeyChecking=no -i prod-key.pem ${{ secrets.EC2_PROD_USER }}@${{ secrets.PROD_HOST }} "sudo rm -rf /var/www/react-app/*"

          echo "Copying new build..."
          scp -o StrictHostKeyChecking=no -i prod-key.pem -r build/* ${{ secrets.EC2_PROD_USER }}@${{ secrets.PROD_HOST }}:/tmp/build/

          echo "Moving files to Nginx directory..."
          ssh -o StrictHostKeyChecking=no -i prod-key.pem ${{ secrets.EC2_PROD_USER }}@${{ secrets.PROD_HOST }} "sudo mv /tmp/build/* /var/www/react-app/"

          echo "Restarting Nginx..."
          ssh -o StrictHostKeyChecking=no -i prod-key.pem ${{ secrets.EC2_PROD_USER }}@${{ secrets.PROD_HOST }} "sudo systemctl restart nginx"
